import { CEOSummary } from './types';

export const CEO_DATA: Record<string, CEOSummary[]> = {
  "AI & Deep Tech": [
    { name: "Jensen Huang", company: "NVIDIA" },
    { name: "Sam Altman", company: "OpenAI" },
    { name: "Demis Hassabis", company: "Google DeepMind" },
    { name: "Dario Amodei", company: "Anthropic" },
    { name: "Elon Musk", company: "xAI, Tesla, SpaceX" },
    { name: "Andrew Ng", company: "Google Brain, Coursera" },
    { name: "Fei-Fei Li", company: "Stanford HAI, ImageNet" },
    { name: "Mustafa Suleyman", company: "Microsoft AI, Inflection" },
    { name: "Satya Nadella", company: "Microsoft" },
    { name: "Sundar Pichai", company: "Google, Alphabet" },
    { name: "Geoffrey Hinton", company: "Godfather of AI" },
    { name: "Yann LeCun", company: "Meta AI" },
    { name: "Ilya Sutskever", company: "OpenAI, SSI" },
    { name: "Mira Murati", company: "OpenAI" },
    { name: "Emad Mostaque", company: "Stability AI" },
    { name: "David Luan", company: "Adept AI" },
    { name: "William Chen", company: "Various AI Research" },
    { name: "Guan Wang", company: "AI Research" },
    { name: "Richard Socher", company: "You.com, Salesforce" },
    { name: "Alexandr Wang", company: "Scale AI" },
    { name: "Andrej Karpathy", company: "OpenAI, Tesla Autopilot" },
    { name: "Sebastian Thrun", company: "Udacity, Google X" },
    { name: "Sergei Brin", company: "Google" },
    { name: "Larry Page", company: "Google" },
    { name: "Patrick Collison", company: "Stripe" },
    { name: "John Carmack", company: "AGI Research, Oculus" },
    { name: "Kai-Fu Lee", company: "01.AI, Sinovation Ventures" },
    { name: "Jack Clark", company: "Anthropic" },
    { name: "Rohit Krishnan", company: "Venture Capital" },
    { name: "Timnit Gebru", company: "DAIR Institute" }
  ],
  "App & SaaS": [
    { name: "Marc Benioff", company: "Salesforce" },
    { name: "Tobias Lütke", company: "Shopify" },
    { name: "Eric Yuan", company: "Zoom" },
    { name: "Melanie Perkins", company: "Canva" },
    { name: "Stewart Butterfield", company: "Slack" },
    { name: "Patrick Collison", company: "Stripe" },
    { name: "John Collison", company: "Stripe" },
    { name: "Drew Houston", company: "Dropbox" },
    { name: "Aaron Levie", company: "Box" },
    { name: "Mike Cannon-Brookes", company: "Atlassian" },
    { name: "Scott Farquhar", company: "Atlassian" },
    { name: "Dylan Field", company: "Figma" },
    { name: "Ivan Zhao", company: "Notion" },
    { name: "Jeff Lawson", company: "Twilio" },
    { name: "Sid Sijbrandij", company: "GitLab" },
    { name: "Todd McKinnon", company: "Okta" },
    { name: "Lew Cirne", company: "New Relic" },
    { name: "Girish Mathrubootham", company: "Freshworks" },
    { name: "Edith Harbaugh", company: "LaunchDarkly" },
    { name: "Shantanu Narayen", company: "Adobe" },
    { name: "Aneel Bhusri", company: "Workday" },
    { name: "Jay Chaudhry", company: "Zscaler" },
    { name: "Jennifer Tejada", company: "PagerDuty" },
    { name: "Yamini Rangan", company: "HubSpot" },
    { name: "Therese Tucker", company: "BlackLine" },
    { name: "René Lacerte", company: "Bill.com" },
    { name: "Tien Tzuo", company: "Zuora" },
    { name: "Nick Mehta", company: "Gainsight" },
    { name: "Tooey Courtemanche", company: "Procore" },
    { name: "Mathilde Collin", company: "Front" }
  ],
  "Authors": [
    { name: "J. K. Rowling", company: "Harry Potter" },
    { name: "James Patterson", company: "Alex Cross Series" },
    { name: "Stephen King", company: "IT, The Shining" },
    { name: "John Grisham", company: "The Firm" },
    { name: "George R.R. Martin", company: "Game of Thrones" },
    { name: "Danielle Steel", company: "Romance Novels" },
    { name: "Nora Roberts", company: "Romance Novels" },
    { name: "Paulo Coelho", company: "The Alchemist" },
    { name: "Sidney Sheldon", company: "Master of the Game" },
    { name: "Tim Ferriss", company: "The 4-Hour Workweek" },
    { name: "Malcolm Gladwell", company: "Outliers, Blink" },
    { name: "Simon Sinek", company: "Start With Why" },
    { name: "Jim Collins", company: "Good to Great" },
    { name: "Stephen R. Covey", company: "7 Habits" },
    { name: "Tony Robbins", company: "Money: Master the Game" },
    { name: "Robert T. Kiyosaki", company: "Rich Dad Poor Dad" },
    { name: "Eric Ries", company: "The Lean Startup" },
    { name: "Robert Greene", company: "48 Laws of Power" },
    { name: "Dr. Seuss (Theodore Geisel)", company: "Children's Books" },
    { name: "Adam Grant", company: "Think Again" },
    { name: "Dan Pink", company: "Drive" },
    { name: "W. Chan Kim", company: "Blue Ocean Strategy" },
    { name: "Renée Mauborgne", company: "Blue Ocean Strategy" },
    { name: "Chris Voss", company: "Never Split the Difference" },
    { name: "Mike Michalowicz", company: "Profit First" },
    { name: "Chris Guillebeau", company: "$100 Startup" },
    { name: "Clayton Christensen", company: "Innovator's Dilemma" },
    { name: "Jeffrey Archer", company: "Kane and Abel" },
    { name: "Seth Godin", company: "Purple Cow" },
    { name: "James Clear", company: "Atomic Habits" }
  ],
  "Biotech & Life Sciences": [
    { name: "Patrick Soon-Shiong", company: "NantWorks" },
    { name: "George Church", company: "Harvard Genetics" },
    { name: "Jennifer Doudna", company: "CRISPR" },
    { name: "Emmanuelle Charpentier", company: "CRISPR" },
    { name: "Robert Langer", company: "Moderna" },
    { name: "Noubar Afeyan", company: "Flagship Pioneering" },
    { name: "Stéphane Bancel", company: "Moderna" },
    { name: "Albert Bourla", company: "Pfizer" },
    { name: "Ugur Sahin", company: "BioNTech" },
    { name: "Katalin Karikó", company: "mRNA Technology" },
    { name: "Eric Yuan", company: "Biotech Investor" },
    { name: "Mark Bamford", company: "Biotech" },
    { name: "Anne Wojcicki", company: "23andMe" },
    { name: "Craig Venter", company: "Human Genome Project" },
    { name: "Reed Hastings", company: "Biotech Philanthropy" },
    { name: "Michelle McMurry-Heath", company: "BIO" },
    { name: "Vivek Ramaswamy", company: "Roivant Sciences" },
    { name: "Feng Zhang", company: "Broad Institute" },
    { name: "Chris Gibson", company: "Recursion" },
    { name: "Reshma Shetty", company: "Ginkgo Bioworks" },
    { name: "Dean Kamen", company: "DEKA" },
    { name: "Eric Topol", company: "Scripps Research" },
    { name: "Joseph Jimenez", company: "Novartis" },
    { name: "Frans van Houten", company: "Philips" },
    { name: "Paul Hudson", company: "Sanofi" },
    { name: "Leonard Schleifer", company: "Regeneron" },
    { name: "David Ricks", company: "Eli Lilly" },
    { name: "Alex Gorsky", company: "Johnson & Johnson" },
    { name: "Vas Narasimhan", company: "Novartis" }
  ],
  "Consumer Tech": [
    { name: "Tim Cook", company: "Apple" },
    { name: "Mark Zuckerberg", company: "Meta" },
    { name: "Jeff Bezos", company: "Amazon" },
    { name: "Evan Spiegel", company: "Snapchat" },
    { name: "Brian Chesky", company: "Airbnb" },
    { name: "Daniel Ek", company: "Spotify" },
    { name: "Reed Hastings", company: "Netflix" },
    { name: "Susan Wojcicki", company: "YouTube" },
    { name: "Kevin Systrom", company: "Instagram" },
    { name: "Mike Krieger", company: "Instagram" },
    { name: "Travis Kalanick", company: "Uber" },
    { name: "Dara Khosrowshahi", company: "Uber" },
    { name: "Marc Benioff", company: "Salesforce" },
    { name: "Sheryl Sandberg", company: "Meta" },
    { name: "Hiroshi Mikitani", company: "Rakuten" },
    { name: "Colin Huang", company: "Pinduoduo" },
    { name: "Lei Jun", company: "Xiaomi" },
    { name: "Pony Ma", company: "Tencent" },
    { name: "Zhang Yiming", company: "ByteDance (TikTok)" },
    { name: "William Ding", company: "NetEase" },
    { name: "Eric Yuan", company: "Zoom" },
    { name: "Whitney Wolfe Herd", company: "Bumble" },
    { name: "Ben Silbermann", company: "Pinterest" },
    { name: "Stewart Butterfield", company: "Slack" },
    { name: "Garrett Camp", company: "Uber" },
    { name: "Drew Houston", company: "Dropbox" },
    { name: "Lisa Su", company: "AMD" },
    { name: "Hiroshi Ishiguro", company: "Robotics" },
    { name: "Jensen Huang", company: "NVIDIA" },
    { name: "Evan Williams", company: "Twitter, Medium" }
  ],
  "Content Creator": [
    { name: "Gary Vaynerchuk", company: "VaynerMedia" },
    { name: "Tim Ferriss", company: "The 4-Hour Workweek" },
    { name: "MrBeast (Jimmy Donaldson)", company: "YouTube" },
    { name: "Emma Chamberlain", company: "Chamberlain Coffee" },
    { name: "Rhett & Link", company: "Good Mythical Morning" },
    { name: "Michelle Phan", company: "IPSY" },
    { name: "Casey Neistat", company: "YouTube, Beme" },
    { name: "MKBHD (Marques Brownlee)", company: "Tech Reviewer" },
    { name: "Ali Abdaal", company: "Productivity Guru" },
    { name: "Pat Flynn", company: "Smart Passive Income" },
    { name: "Amy Porterfield", company: "Online Marketing" },
    { name: "Kat Norton (Miss Excel)", company: "Microsoft MVP" },
    { name: "Marianna Hewitt", company: "Summer Fridays" },
    { name: "Negin Mirsalehi", company: "Gisou" },
    { name: "Zach King", company: "Digital Magician" },
    { name: "Shaun McBride (Shonduras)", company: "Spacestation" },
    { name: "Lilly Singh", company: "Unicorn Island" },
    { name: "Markiplier (Mark Fischbach)", company: "YouTube" },
    { name: "Dhar Mann", company: "Dhar Mann Studios" },
    { name: "Dude Perfect", company: "Sports Entertainment" },
    { name: "Nathan Barry", company: "ConvertKit" },
    { name: "Rand Fishkin", company: "SparkToro" },
    { name: "Alex Hormozi", company: "Acquisition.com" },
    { name: "Jacksepticeye (Seán McLoughlin)", company: "YouTube" },
    { name: "Linus Sebastian (Linus Tech Tips)", company: "LMG" },
    { name: "Chiara Ferragni", company: "The Blonde Salad" },
    { name: "Andrew Rea (Binging with Babish)", company: "Babish Culinary Universe" },
    { name: "Jenna Kutcher", company: "Goal Digger Podcast" },
    { name: "Seth Godin", company: "Marketing" },
    { name: "James Clear", company: "Atomic Habits" }
  ],
  "Crypto & Web3": [
    { name: "Vitalik Buterin", company: "Ethereum" },
    { name: "Brian Armstrong", company: "Coinbase" },
    { name: "Michael Saylor", company: "MicroStrategy" },
    { name: "Barry Silbert", company: "Digital Currency Group" },
    { name: "Charles Hoskinson", company: "Cardano" },
    { name: "Gavin Wood", company: "Polkadot, Ethereum" },
    { name: "Brock Pierce", company: "Tether" },
    { name: "Cameron Winklevoss", company: "Gemini" },
    { name: "Tyler Winklevoss", company: "Gemini" },
    { name: "Anatoly Yakovenko", company: "Solana" },
    { name: "Cathie Wood", company: "ARK Invest" },
    { name: "Jack Dorsey", company: "Block, Bitcoin" },
    { name: "Hayden Adams", company: "Uniswap" },
    { name: "Fred Ehrsam", company: "Paradigm" },
    { name: "Jesse Powell", company: "Kraken" },
    { name: "Brad Garlinghouse", company: "Ripple" },
    { name: "David Marcus", company: "Lightspark" },
    { name: "Balaji Srinivasan", company: "Network State" },
    { name: "Robert Leshner", company: "Compound" },
    { name: "Sam Cassatt", company: "ConsenSys" },
    { name: "Stani Kulechov", company: "Aave" },
    { name: "Rune Christensen", company: "MakerDAO" },
    { name: "Anatoly Baks", company: "Solana Labs" },
    { name: "Sergey Nazarov", company: "Chainlink" },
    { name: "Lisa Nestor", company: "Stellar" }
  ],
  "E-Commerce & Retail": [
    { name: "Jeff Bezos", company: "Amazon" },
    { name: "Jack Ma", company: "Alibaba" },
    { name: "Colin Huang", company: "Pinduoduo" },
    { name: "Zhang Yong", company: "Alibaba" },
    { name: "Daniel Zhang", company: "Alibaba" },
    { name: "Richard Liu", company: "JD.com" },
    { name: "Doug McMillon", company: "Walmart" },
    { name: "Brian Cornell", company: "Target" },
    { name: "Hiroshi Mikitani", company: "Rakuten" },
    { name: "Tobias Lütke", company: "Shopify" },
    { name: "Melanie Perkins", company: "Canva" },
    { name: "Patrick Collison", company: "Stripe" },
    { name: "Hamdi Ulukaya", company: "Chobani" },
    { name: "Jeff Weiner", company: "LinkedIn" },
    { name: "Katrina Lake", company: "Stitch Fix" },
    { name: "Tony Xu", company: "DoorDash" },
    { name: "Apoorva Mehta", company: "Instacart" },
    { name: "Falguni Nayar", company: "Nykaa" },
    { name: "Binny Bansal", company: "Flipkart" },
    { name: "Sachin Bansal", company: "Flipkart" },
    { name: "Kunal Bahl", company: "Snapdeal" },
    { name: "Mukesh Bansal", company: "Myntra" },
    { name: "Lei Jun", company: "Xiaomi" },
    { name: "Stuart Landesberg", company: "Grove Collaborative" },
    { name: "Michael Rubin", company: "Fanatics" },
    { name: "Michelle Gass", company: "Kohl's" },
    { name: "Eddie Wu", company: "Alibaba" },
    { name: "Matt Mullenweg", company: "WordPress, Automattic" },
    { name: "Dave Gilboa", company: "Warby Parker" }
  ],
  "Digital Marketing": [
    { name: "Neil Patel", company: "NP Digital" },
    { name: "Darren Rowse", company: "ProBlogger" },
    { name: "Avinash Kaushik", company: "Google Analytics" },
    { name: "Ryan Deiss", company: "DigitalMarketer" },
    { name: "Noah Kagan", company: "AppSumo" },
    { name: "Jeff Walker", company: "Product Launch Formula" },
    { name: "Ann Handley", company: "MarketingProfs" },
    { name: "Joe Pulizzi", company: "Content Marketing Institute" },
    { name: "Brian Dean", company: "Backlinko" },
    { name: "Marcus Sheridan", company: "River Pools" },
    { name: "Joanna Wiebe", company: "Copyhackers" },
    { name: "Oren Klaff", company: "Pitch Anything" },
    { name: "Jon Loomer", company: "Facebook Marketing" },
    { name: "Pamela Slim", company: "Escape from Cubicle Nation" },
    { name: "Jay Baer", company: "Convince & Convert" },
    { name: "Dharmesh Shah", company: "HubSpot" },
    { name: "Scott Brinker", company: "Chief Martec" },
    { name: "Michael Stelzner", company: "Social Media Examiner" },
    { name: "Mari Smith", company: "Facebook Marketing" },
    { name: "Kim Garst", company: "Social Media" },
    { name: "Perry Marshall", company: "Google AdWords" },
    { name: "Mike Rhodes", company: "WebSavvy" },
    { name: "Vanessa Van Edwards", company: "Science of People" },
    { name: "Dorie Clark", company: "Reinventing You" },
    { name: "Sujan Patel", company: "Mailshake" },
    { name: "Ryan Stewart", company: "WEBRIS" },
    { name: "Seth Godin", company: "This is Marketing" },
    { name: "Rand Fishkin", company: "SparkToro, Moz" },
    { name: "Gary Vaynerchuk", company: "VaynerMedia" },
    { name: "Ezra Firestone", company: "Smart Marketer" }
  ],
  "Filmmakers": [
    { name: "George Lucas", company: "Star Wars" },
    { name: "Steven Spielberg", company: "Jaws, Jurassic Park" },
    { name: "Tyler Perry", company: "Tyler Perry Studios" },
    { name: "Peter Jackson", company: "Lord of the Rings" },
    { name: "James Cameron", company: "Avatar, Titanic" },
    { name: "Oprah Winfrey", company: "Harpo Productions" },
    { name: "J.J. Abrams", company: "Bad Robot" },
    { name: "Reese Witherspoon", company: "Hello Sunshine" },
    { name: "Dwayne \"The Rock\" Johnson", company: "Seven Bucks Productions" },
    { name: "Shonda Rhimes", company: "Shondaland" },
    { name: "Ryan Murphy", company: "American Horror Story" },
    { name: "Ava DuVernay", company: "ARRAY" },
    { name: "Will Packer", company: "Will Packer Productions" },
    { name: "Jerry Bruckheimer", company: "Top Gun, Pirates" },
    { name: "Ridley Scott", company: "Alien, Gladiator" },
    { name: "Mark Burnett", company: "Survivor, The Voice" },
    { name: "Christopher Nolan", company: "Inception, Dark Knight" },
    { name: "Guillermo del Toro", company: "Shape of Water" },
    { name: "Ron Howard", company: "Imagine Entertainment" },
    { name: "Brian Grazer", company: "Imagine Entertainment" },
    { name: "Jordan Peele", company: "Monkeypaw Productions" },
    { name: "Megan Ellison", company: "Annapurna Pictures" },
    { name: "M. Night Shyamalan", company: "Sixth Sense" },
    { name: "Jason Blum", company: "Blumhouse" },
    { name: "Judd Apatow", company: "Apatow Productions" },
    { name: "Alfonso Cuarón", company: "Gravity, Roma" },
    { name: "Robert Rodriguez", company: "Troublemaker Studios" },
    { name: "Angelina Jolie", company: "Director" },
    { name: "Clint Eastwood", company: "Malpaso Productions" },
    { name: "Quentin Tarantino", company: "Pulp Fiction" }
  ],
  "Finance & VC": [
    { name: "Warren Buffett", company: "Berkshire Hathaway" },
    { name: "Charlie Munger", company: "Berkshire Hathaway" },
    { name: "Jamie Dimon", company: "JPMorgan Chase" },
    { name: "Ray Dalio", company: "Bridgewater Associates" },
    { name: "Ken Griffin", company: "Citadel" },
    { name: "Larry Fink", company: "BlackRock" },
    { name: "Stephen Schwarzman", company: "Blackstone" },
    { name: "Henry Kravis", company: "KKR" },
    { name: "David Rubenstein", company: "Carlyle Group" },
    { name: "Bill Ackman", company: "Pershing Square" },
    { name: "Cathie Wood", company: "ARK Invest" },
    { name: "Masayoshi Son", company: "SoftBank" },
    { name: "Jim Simons", company: "Renaissance Technologies" },
    { name: "Michael Bloomberg", company: "Bloomberg L.P." },
    { name: "Robert Smith", company: "Vista Equity" },
    { name: "James Gorman", company: "Morgan Stanley" },
    { name: "Abigail Johnson", company: "Fidelity" },
    { name: "Adena Friedman", company: "Nasdaq" },
    { name: "Mary Callahan Erdoes", company: "JPMorgan" },
    { name: "Stanley Druckenmiller", company: "Duquesne Family Office" },
    { name: "George Soros", company: "Soros Fund" },
    { name: "Peter Thiel", company: "Founders Fund" },
    { name: "Marc Andreessen", company: "a16z" },
    { name: "Ben Horowitz", company: "a16z" },
    { name: "Chamath Palihapitiya", company: "Social Capital" },
    { name: "Naval Ravikant", company: "AngelList" },
    { name: "Li Ka-Shing", company: "CK Hutchison" },
    { name: "Carlos Slim", company: "América Móvil" },
    { name: "Mukesh Ambani", company: "Reliance Industries" },
    { name: "Aliko Dangote", company: "Dangote Group" }
  ],
  "Energy & Cleantech": [
    { name: "Elon Musk", company: "Tesla Energy" },
    { name: "JB Straubel", company: "Redwood Materials" },
    { name: "Patrick Pouyanné", company: "TotalEnergies" },
    { name: "Bernard Looney", company: "BP" },
    { name: "Amin Nasser", company: "Saudi Aramco" },
    { name: "Vicki Hollub", company: "Occidental Petroleum" },
    { name: "Darren Woods", company: "ExxonMobil" },
    { name: "Daniel Yergin", company: "IHS Markit" },
    { name: "Fatih Birol", company: "IEA" },
    { name: "Andrew Forrest", company: "Fortescue Future Industries" },
    { name: "Henrik Andersen", company: "Vestas" },
    { name: "Anthony Pratt", company: "Pratt Industries" },
    { name: "Ernest Moniz", company: "Energy Futures Initiative" },
    { name: "Bill Gates", company: "Breakthrough Energy" },
    { name: "Peter Rive", company: "SolarCity" },
    { name: "Lyndon Rive", company: "SolarCity" },
    { name: "Thomas Siebel", company: "C3 AI" },
    { name: "Achal Sondhi", company: "Fluence" },
    { name: "Francesco Starace", company: "Enel" },
    { name: "Eric Yuan", company: "Investor" },
    { name: "Li Zhenguo", company: "LONGi Green Energy" },
    { name: "Zhang Lei", company: "Envision Group" },
    { name: "Wang Chuanfu", company: "BYD" },
    { name: "Harold Hamm", company: "Continental Resources" },
    { name: "John Hess", company: "Hess Corporation" },
    { name: "Charif Souki", company: "Tellurian" },
    { name: "Richard Kinder", company: "Kinder Morgan" },
    { name: "Tom Werner", company: "SunPower" },
    { name: "Scott Jacobs", company: "Generate Capital" },
    { name: "Jigar Shah", company: "DOE Loan Programs" }
  ],
  "EV & Mobility": [
    { name: "Elon Musk", company: "Tesla" },
    { name: "Akio Toyoda", company: "Toyota" },
    { name: "Oliver Blume", company: "Volkswagen Group" },
    { name: "Mary Barra", company: "GM" },
    { name: "Jim Farley", company: "Ford" },
    { name: "Carlos Tavares", company: "Stellantis" },
    { name: "Herbert Diess", company: "Volkswagen (Former)" },
    { name: "Li Shufu", company: "Geely, Volvo" },
    { name: "Wang Chuanfu", company: "BYD" },
    { name: "Peter Rawlinson", company: "Lucid Motors" },
    { name: "RJ Scaringe", company: "Rivian" },
    { name: "Henrik Fisker", company: "Fisker" },
    { name: "He Xiaopeng", company: "XPeng" },
    { name: "William Li", company: "NIO" },
    { name: "Lei Jun", company: "Xiaomi EV" },
    { name: "Taizo Son", company: "Mistletoe" },
    { name: "Ola Källenius", company: "Mercedes-Benz" },
    { name: "Luca de Meo", company: "Renault" },
    { name: "Dieter Zetsche", company: "Daimler (Former)" },
    { name: "Hiroshi Mikitani", company: "Rakuten" },
    { name: "Naveen Munjal", company: "Hero Electric" },
    { name: "Min Liang Tan", company: "Razer" },
    { name: "Tony Aquila", company: "Canoo" },
    { name: "Mate Rimac", company: "Rimac Automobili" },
    { name: "Horacio Pagani", company: "Pagani" },
    { name: "Frank Stephenson", company: "Car Designer" },
    { name: "Christian von Koenigsegg", company: "Koenigsegg" },
    { name: "Daniel Li", company: "Geely" }
  ],
  "Cybersecurity & Defense": [
    { name: "Eugene Kaspersky", company: "Kaspersky Lab" },
    { name: "George Kurtz", company: "CrowdStrike" },
    { name: "Nir Zuk", company: "Palo Alto Networks" },
    { name: "Kevin Mandia", company: "Mandiant" },
    { name: "Gil Shwed", company: "Check Point" },
    { name: "Tom Kennedy", company: "Raytheon" },
    { name: "Marillyn Hewson", company: "Lockheed Martin" },
    { name: "Eric Schmidt", company: "Google (Former)" },
    { name: "Alex Karp", company: "Palantir" },
    { name: "Peter Thiel", company: "Palantir" },
    { name: "Keith Alexander", company: "IronNet" },
    { name: "Renee James", company: "Ampere" },
    { name: "Robert Herjavec", company: "Herjavec Group" },
    { name: "Chris Inglis", company: "National Cyber Director" },
    { name: "Anne Neuberger", company: "NSA" },
    { name: "Dmitri Alperovitch", company: "CrowdStrike" },
    { name: "Katie Moussouris", company: "Luta Security" },
    { name: "Bruce Schneier", company: "Cryptographer" },
    { name: "Mudge Peiter", company: "Security Researcher" },
    { name: "J.J. Gertler", company: "Defense Analyst" },
    { name: "Palmer Luckey", company: "Anduril" },
    { name: "Brian Murphy", company: "ReliaQuest" },
    { name: "Chris Krebs", company: "CISA" },
    { name: "Nicole Eagan", company: "Darktrace" },
    { name: "Jay Chaudhry", company: "Zscaler" },
    { name: "Ashar Aziz", company: "FireEye" },
    { name: "Sam Curry", company: "Cybereason" },
    { name: "William Evanina", company: "NCSC" },
    { name: "Theresa Payton", company: "Fortalice Solutions" },
    { name: "Ken Xie", company: "Fortinet" }
  ],
  "Media & Entertainment": [
    { name: "Reed Hastings", company: "Netflix" },
    { name: "Ted Sarandos", company: "Netflix" },
    { name: "Bob Iger", company: "Disney" },
    { name: "Kevin Feige", company: "Marvel Studios" },
    { name: "Shonda Rhimes", company: "Shondaland" },
    { name: "Casey Bloys", company: "HBO" },
    { name: "Rupert Murdoch", company: "News Corp" },
    { name: "Lachlan Murdoch", company: "Fox Corp" },
    { name: "David Zaslav", company: "Warner Bros. Discovery" },
    { name: "Ryan Murphy", company: "Netflix" },
    { name: "Tim Cook", company: "Apple TV+" },
    { name: "Daniel Ek", company: "Spotify" },
    { name: "Jimmy Iovine", company: "Interscope, Beats" },
    { name: "Susan Wojcicki", company: "YouTube" },
    { name: "Neal Mohan", company: "YouTube" },
    { name: "Mark Zuckerberg", company: "Meta" },
    { name: "Evan Spiegel", company: "Snapchat" },
    { name: "Kevin Systrom", company: "Instagram" },
    { name: "Scooter Braun", company: "Hybe America" },
    { name: "Jay-Z", company: "Roc Nation" },
    { name: "Beyoncé", company: "Parkwood Entertainment" },
    { name: "Oprah Winfrey", company: "OWN" },
    { name: "Tyler Perry", company: "Tyler Perry Studios" },
    { name: "Kevin Hart", company: "HartBeat" },
    { name: "Reese Witherspoon", company: "Hello Sunshine" },
    { name: "Lin-Manuel Miranda", company: "Hamilton" },
    { name: "Ryan Reynolds", company: "Maximum Effort" },
    { name: "Donald Glover", company: "Gilga" },
    { name: "Bong Joon-ho", company: "Parasite" },
    { name: "Christopher Nolan", company: "Syncopy" }
  ],
  "Gaming & Esports": [
    { name: "Gabe Newell", company: "Valve, Steam" },
    { name: "Tim Sweeney", company: "Epic Games" },
    { name: "Jensen Huang", company: "NVIDIA" },
    { name: "Min-Liang Tan", company: "Razer" },
    { name: "Bobby Kotick", company: "Activision Blizzard" },
    { name: "Yves Guillemot", company: "Ubisoft" },
    { name: "Hideo Kojima", company: "Kojima Productions" },
    { name: "Phil Spencer", company: "Xbox" },
    { name: "Shigeru Miyamoto", company: "Nintendo" },
    { name: "Satoru Iwata", company: "Nintendo" },
    { name: "Junichi Masuda", company: "Game Freak (Pokémon)" },
    { name: "Todd Howard", company: "Bethesda" },
    { name: "Ken Levine", company: "Ghost Story Games" },
    { name: "Pete Hines", company: "Bethesda" },
    { name: "John Carmack", company: "id Software" },
    { name: "John Romero", company: "Doom" },
    { name: "Naoki Yoshida", company: "Square Enix (FFXIV)" },
    { name: "Hajime Tabata", company: "JP Games" },
    { name: "Kazunori Yamauchi", company: "Polyphony Digital" },
    { name: "Amy Hennig", company: "Uncharted" },
    { name: "Bonnie Ross", company: "Halo" },
    { name: "Strauss Zelnick", company: "Take-Two" },
    { name: "Brandon Beck", company: "Riot Games" },
    { name: "Marc Merrill", company: "Riot Games" },
    { name: "Niklas Hed", company: "Rovio (Angry Birds)" },
    { name: "Jens Hilgers", company: "G2 Esports" },
    { name: "Victor Goossens", company: "Team Liquid" },
    { name: "Matthew Haag", company: "100 Thieves" },
    { name: "Tyler Blevins", company: "Ninja" },
    { name: "Richard Lewis", company: "Esports Journalist" }
  ],
  "Real Estate & PropTech": [
    { name: "Stephen Ross", company: "Related Companies" },
    { name: "Donald Bren", company: "Irvine Company" },
    { name: "Harry Triguboff", company: "Meriton" },
    { name: "Wang Jianlin", company: "Wanda Group" },
    { name: "Joseph Lau", company: "Chinese Estates" },
    { name: "Sam Zell", company: "Equity Group" },
    { name: "Jeff Greene", company: "Real Estate" },
    { name: "Frank Lowy", company: "Westfield" },
    { name: "Jonathan Gray", company: "Blackstone" },
    { name: "Bruce Flatt", company: "Brookfield" },
    { name: "Robert Reffkin", company: "Compass" },
    { name: "Gary Keller", company: "Keller Williams" },
    { name: "Ryan Serhant", company: "SERHANT." },
    { name: "Grant Cardone", company: "Cardone Capital" },
    { name: "Rick Caruso", company: "Caruso" },
    { name: "Jerry Speyer", company: "Tishman Speyer" },
    { name: "Neil Bluhm", company: "Walton Street" },
    { name: "Walter Scott Jr.", company: "Kiewit" },
    { name: "Dan Gilbert", company: "Rocket Companies" },
    { name: "Mortimer Zuckerman", company: "Boston Properties" },
    { name: "Barry Sternlicht", company: "Starwood" },
    { name: "Steve Witkoff", company: "Witkoff Group" },
    { name: "David Walentas", company: "Two Trees" },
    { name: "Stephen Schwarzman", company: "Blackstone" },
    { name: "Zhang Xin", company: "SOHO China" },
    { name: "Pan Shiyi", company: "SOHO China" },
    { name: "Adam Neumann", company: "Flow, WeWork" },
    { name: "Miguel McKelvey", company: "WeWork" }
  ],
  "FoodTech & Agriculture": [
    { name: "Ethan Brown", company: "Beyond Meat" },
    { name: "Patrick Brown", company: "Impossible Foods" },
    { name: "Hamdi Ulukaya", company: "Chobani" },
    { name: "José Andrés", company: "World Central Kitchen" },
    { name: "Kimbal Musk", company: "The Kitchen" },
    { name: "Tony Xu", company: "DoorDash" },
    { name: "Apoorva Mehta", company: "Instacart" },
    { name: "Falguni Nayar", company: "Nykaa" },
    { name: "Julia Collins", company: "Planet FWD" },
    { name: "Emily Broad Leib", company: "Food Law Policy" },
    { name: "David Barber", company: "Almanac" },
    { name: "Eyal Shani", company: "Miznon" },
    { name: "Will Shu", company: "Deliveroo" },
    { name: "Ben Chestnut", company: "Mailchimp (Acquired)" },
    { name: "Walter Robb", company: "Whole Foods" },
    { name: "Daniel Zhang", company: "Alibaba" },
    { name: "Charles Butt", company: "H-E-B" },
    { name: "Jim Snee", company: "Hormel" },
    { name: "Emmanuel Faber", company: "Danone (Former)" },
    { name: "Jan Zijderveld", company: "Avon (Former)" },
    { name: "Li Ning", company: "Li-Ning" },
    { name: "James Quincey", company: "Coca-Cola" },
    { name: "Indra Nooyi", company: "PepsiCo (Former)" },
    { name: "Denise Morrison", company: "Campbell Soup" },
    { name: "Dirk Van de Put", company: "Mondelez" },
    { name: "Zhang Yong", company: "Haidilao" },
    { name: "Colin Huang", company: "Pinduoduo" },
    { name: "Uğur Şahin", company: "BioNTech" },
    { name: "Ilkka Paananen", company: "Supercell" },
    { name: "Massimo Bottura", company: "Osteria Francescana" }
  ],
  "Healthcare & Medical Devices": [
    { name: "Bernard Tyson", company: "Kaiser Permanente" },
    { name: "Alex Gorsky", company: "J&J" },
    { name: "Paul Hudson", company: "Sanofi" },
    { name: "Stéphane Bancel", company: "Moderna" },
    { name: "Albert Bourla", company: "Pfizer" },
    { name: "Lisa Suennen", company: "Venture Valkyrie" },
    { name: "Anne Wojcicki", company: "23andMe" },
    { name: "Amir Rubin", company: "One Medical" },
    { name: "Frans van Houten", company: "Philips" },
    { name: "David Ricks", company: "Eli Lilly" },
    { name: "Omar Ishrak", company: "Medtronic" },
    { name: "Geoff Martha", company: "Medtronic" },
    { name: "Tim Cook", company: "Apple Health" },
    { name: "Judy Faulkner", company: "Epic Systems" },
    { name: "Samuel Hazen", company: "HCA Healthcare" },
    { name: "Karen Lynch", company: "CVS Health" },
    { name: "Gail Boudreaux", company: "Elevance Health" },
    { name: "David Cordani", company: "Cigna" },
    { name: "Vivek Murthy", company: "US Surgeon General" },
    { name: "Eric Topol", company: "Scripps Research" },
    { name: "Reshma Shetty", company: "Ginkgo Bioworks" },
    { name: "Chris Gibson", company: "Recursion" },
    { name: "Avidit Acharya", company: "Stanford" },
    { name: "Dean Kamen", company: "DEKA" },
    { name: "Mark Bertolini", company: "Aetna" },
    { name: "Larry Merlo", company: "CVS Health" },
    { name: "Gregory Adams", company: "Kaiser Permanente" },
    { name: "Richard Feachem", company: "Global Fund" },
    { name: "Jim Rechtin", company: "Envision" },
    { name: "Sarah London", company: "Centene" }
  ],
  "Telecom & Semiconductors": [
    { name: "Lisa Su", company: "AMD" },
    { name: "Jensen Huang", company: "NVIDIA" },
    { name: "Pat Gelsinger", company: "Intel" },
    { name: "Cristiano Amon", company: "Qualcomm" },
    { name: "Ren Zhengfei", company: "Huawei" },
    { name: "Liang Hua", company: "Huawei" },
    { name: "Andy Jassy", company: "Amazon Web Services" },
    { name: "Satya Nadella", company: "Microsoft Azure" },
    { name: "Tim Cook", company: "Apple Silicon" },
    { name: "Sundar Pichai", company: "Google Cloud" },
    { name: "Morris Chang", company: "TSMC" },
    { name: "C.C. Wei", company: "TSMC" },
    { name: "Mark Liu", company: "TSMC" },
    { name: "Reed Hastings", company: "Netflix" },
    { name: "Marc Benioff", company: "Salesforce" },
    { name: "Sanjay Mehrotra", company: "Micron" },
    { name: "Steve Mollenkopf", company: "Qualcomm" },
    { name: "Arvind Krishna", company: "IBM" },
    { name: "Safra Catz", company: "Oracle" },
    { name: "Larry Ellison", company: "Oracle" },
    { name: "Michael Dell", company: "Dell" },
    { name: "Chuck Robbins", company: "Cisco" },
    { name: "Hans Vestberg", company: "Verizon" },
    { name: "Mike Sievert", company: "T-Mobile" },
    { name: "Hock Tan", company: "Broadcom" },
    { name: "Su Kai", company: "Telecom" },
    { name: "Charles Liang", company: "Supermicro" },
    { name: "George Kurian", company: "NetApp" },
    { name: "Ken Hu", company: "Huawei" },
    { name: "Yang Chaobin", company: "Huawei" }
  ],
  "Logistics & Supply Chain": [
    { name: "Frederick Smith", company: "FedEx" },
    { name: "David Abney", company: "UPS" },
    { name: "Carol Tomé", company: "UPS" },
    { name: "Ryan Petersen", company: "Flexport" },
    { name: "Daniel Zhang", company: "Cainiao" },
    { name: "Wang Wei", company: "SF Express" },
    { name: "Jack Ma", company: "Alibaba" },
    { name: "Jeff Bezos", company: "Amazon Logistics" },
    { name: "Frank Appel", company: "DHL" },
    { name: "Scott Price", company: "UPS International" },
    { name: "Rolf Habben Jansen", company: "Hapag-Lloyd" },
    { name: "Søren Skou", company: "Maersk" },
    { name: "Vincent Clerc", company: "Maersk" },
    { name: "John Dietrich", company: "Atlas Air" },
    { name: "Guillaume Faury", company: "Airbus" },
    { name: "David Calhoun", company: "Boeing" },
    { name: "John Roberts", company: "JB Hunt" },
    { name: "Andrew Clarke", company: "C.H. Robinson" },
    { name: "Olivier Storch", company: "Geodis" },
    { name: "Bruce Johnson", company: "Express" },
    { name: "Lior Ron", company: "Uber Freight" },
    { name: "Shoichiro Toyoda", company: "Toyota" },
    { name: "Ellen Voie", company: "Women In Trucking" },
    { name: "Rodney McMullen", company: "Kroger" },
    { name: "Janelle Wang", company: "Logistics" },
    { name: "Li Shufu", company: "Geely" },
    { name: "Lei Jun", company: "Xiaomi" },
    { name: "Hiroshi Mikitani", company: "Rakuten Logistics" },
    { name: "Andy Jassy", company: "Amazon" },
    { name: "Tim Cook", company: "Apple Operations" }
  ],
  "Manufacturing & Robotics": [
    { name: "Elon Musk", company: "Tesla, Optimus" },
    { name: "Jensen Huang", company: "NVIDIA Robotics" },
    { name: "Masayoshi Son", company: "SoftBank Robotics" },
    { name: "Hiroshi Ishiguro", company: "Geminoid" },
    { name: "Marc Raibert", company: "Boston Dynamics" },
    { name: "Sam Altman", company: "OpenAI" },
    { name: "Denis Manturov", company: "Industry" },
    { name: "Wang Chuanfu", company: "BYD" },
    { name: "Akio Toyoda", company: "Toyota" },
    { name: "Terry Gou", company: "Foxconn" },
    { name: "Tim Cook", company: "Apple Mfg" },
    { name: "Lisa Su", company: "AMD" },
    { name: "Morris Chang", company: "TSMC" },
    { name: "Kazuo Hirai", company: "Sony" },
    { name: "Natarajan Chandrasekaran", company: "Tata Group" },
    { name: "Dieter Zetsche", company: "Daimler" },
    { name: "Ginni Rometty", company: "IBM" },
    { name: "Larry Culp", company: "GE" },
    { name: "Jim Umpleby", company: "Caterpillar" },
    { name: "Masaaki Kanai", company: "Ryohin Keikaku (Muji)" },
    { name: "James Dyson", company: "Dyson" },
    { name: "Hiroshi Mikitani", company: "Rakuten" },
    { name: "Ryoichi Ueda", company: "Shimadzu" },
    { name: "Shigenobu Nagamori", company: "Nidec" },
    { name: "Young Liu", company: "Foxconn" },
    { name: "Yasuo Takeuchi", company: "Olympus" },
    { name: "Shintaro Yamada", company: "Mercari" },
    { name: "Li Dongsheng", company: "TCL" },
    { name: "William Li", company: "NIO" }
  ],
  "Luxury & Lifestyle": [
    { name: "Bernard Arnault", company: "LVMH" },
    { name: "François-Henri Pinault", company: "Kering" },
    { name: "Miuccia Prada", company: "Prada" },
    { name: "Giorgio Armani", company: "Armani" },
    { name: "Ralph Lauren", company: "Ralph Lauren" },
    { name: "Calvin Klein", company: "Calvin Klein" },
    { name: "Tory Burch", company: "Tory Burch" },
    { name: "Anna Wintour", company: "Vogue" },
    { name: "Domenico De Sole", company: "Tom Ford" },
    { name: "Alessandro Michele", company: "Gucci (Former)" },
    { name: "Virgil Abloh", company: "Off-White, Louis Vuitton" },
    { name: "Karl Lagerfeld", company: "Chanel, Fendi" },
    { name: "Donatella Versace", company: "Versace" },
    { name: "Stella McCartney", company: "Stella McCartney" },
    { name: "Michael Kors", company: "Capri Holdings" },
    { name: "Tom Ford", company: "Tom Ford" },
    { name: "Phoebe Philo", company: "Celine (Former)" },
    { name: "Jonathan Anderson", company: "Loewe" },
    { name: "Remo Ruffini", company: "Moncler" },
    { name: "Nigo", company: "Kenzo" },
    { name: "Adrian Cheng", company: "K11" },
    { name: "Adrian Joffe", company: "Comme des Garçons" },
    { name: "Brunello Cucinelli", company: "Brunello Cucinelli" },
    { name: "Renzo Rosso", company: "Diesel, OTB" },
    { name: "Hubert de Givenchy", company: "Givenchy" },
    { name: "Chiara Ferragni", company: "Influencer" },
    { name: "Kim Jones", company: "Dior Men" },
    { name: "Jerry Lorenzo", company: "Fear of God" },
    { name: "Viren Shah", company: "Luxury" },
    { name: "Victoria Beckham", company: "Victoria Beckham" }
  ],
  "Travel & Hospitality": [
    { name: "Akbar Al Baker", company: "Qatar Airways" },
    { name: "Tim Clark", company: "Emirates" },
    { name: "David Calhoun", company: "Boeing" },
    { name: "Guillaume Faury", company: "Airbus" },
    { name: "Ed Bastian", company: "Delta Air Lines" },
    { name: "Oscar Munoz", company: "United Airlines" },
    { name: "Scott Kirby", company: "United Airlines" },
    { name: "Tony Fernandes", company: "AirAsia" },
    { name: "Bob Chapek", company: "Disney (Former)" },
    { name: "Bob Iger", company: "Disney" },
    { name: "Arne Sorenson", company: "Marriott" },
    { name: "Sébastien Bazin", company: "Accor" },
    { name: "Christopher Nassetta", company: "Hilton" },
    { name: "Anthony Capuano", company: "Marriott" },
    { name: "Brian Chesky", company: "Airbnb" },
    { name: "Joe Gebbia", company: "Airbnb" },
    { name: "Dara Khosrowshahi", company: "Uber" },
    { name: "Travis Kalanick", company: "Uber (Former)" },
    { name: "Glenn Fogel", company: "Booking Holdings" },
    { name: "Mark Okerstrom", company: "Expedia" },
    { name: "Steve Hafner", company: "Kayak" },
    { name: "Trip Hawkins", company: "EA (Game)" },
    { name: "Shinya Katanozaka", company: "ANA Holdings" },
    { name: "Yuji Akasaka", company: "JAL" },
    { name: "Wang Xing", company: "Meituan" },
    { name: "Zhang Yiming", company: "ByteDance" },
    { name: "Frederic Lalonde", company: "Hopper" },
    { name: "Henry Harteveldt", company: "Travel Analyst" },
    { name: "Patrick Pacious", company: "Choice Hotels" },
    { name: "David Kong", company: "Best Western" }
  ],
  "EdTech & Creator Economy": [
    { name: "Salman Khan", company: "Khan Academy" },
    { name: "Ben Nelson", company: "Minerva" },
    { name: "Daphne Koller", company: "Coursera" },
    { name: "Andrew Ng", company: "Coursera, DeepLearning.AI" },
    { name: "Vitalik Buterin", company: "Ethereum" },
    { name: "Marques Brownlee", company: "MKBHD" },
    { name: "MrBeast", company: "YouTube Philanthropy" },
    { name: "Ali Abdaal", company: "Part-Time YouTuber" },
    { name: "Gary Vaynerchuk", company: "VaynerMedia" },
    { name: "Tim Ferriss", company: "4-Hour Workweek" },
    { name: "Lex Fridman", company: "Lex Fridman Podcast" },
    { name: "Jordan Peterson", company: "DailyWire+" },
    { name: "Casey Neistat", company: "Vlogger" },
    { name: "Jimmy Donaldson", company: "MrBeast Burger" },
    { name: "Patrick Bet-David", company: "Valuetainment" },
    { name: "Reid Hoffman", company: "LinkedIn" },
    { name: "Naval Ravikant", company: "AngelList" },
    { name: "Peter Diamandis", company: "XPRIZE" },
    { name: "Tony Robbins", company: "Business Mastery" },
    { name: "Graham Stephan", company: "Real Estate" },
    { name: "Matt D’Avella", company: "Minimalism" },
    { name: "Thomas Frank", company: "College Info Geek" },
    { name: "Colin & Samir", company: "Creator Economy" },
    { name: "Hank Green", company: "Crash Course" },
    { name: "John Green", company: "Crash Course" },
    { name: "Eric Siu", company: "Single Grain" },
    { name: "Neil Patel", company: "Ubersuggest" },
    { name: "Noah Kagan", company: "OkDork" },
    { name: "Ben Shapiro", company: "The Daily Wire" },
    { name: "Dave Ramsey", company: "Ramsey Solutions" }
  ],
  "Information Product": [
    { name: "Tony Robbins", company: "Unleash the Power Within" },
    { name: "Robert T. Kiyosaki", company: "Rich Dad Company" },
    { name: "Tim Ferriss", company: "The 4-Hour Workweek" },
    { name: "Gary Vaynerchuk", company: "VaynerMedia" },
    { name: "Russell Brunson", company: "ClickFunnels" },
    { name: "Amy Porterfield", company: "Digital Course Academy" },
    { name: "Pat Flynn", company: "Smart Passive Income" },
    { name: "Marie Forleo", company: "B-School" },
    { name: "Ramit Sethi", company: "I Will Teach You To Be Rich" },
    { name: "Brendon Burchard", company: "High Performance Habits" },
    { name: "Jeff Walker", company: "Product Launch Formula" },
    { name: "Dean Graziosi", company: "Mastermind.com" },
    { name: "Seth Godin", company: "AltMBA" },
    { name: "James Clear", company: "Atomic Habits" },
    { name: "Mark Manson", company: "Subtle Art" },
    { name: "Vishen Lakhiani", company: "Mindvalley" },
    { name: "Mel Robbins", company: "The 5 Second Rule" },
    { name: "Stu McLaren", company: "Tribes" },
    { name: "Kenny Rueter", company: "Kajabi" },
    { name: "Ankur Nagpal", company: "Teachable" },
    { name: "Nathan Barry", company: "ConvertKit" },
    { name: "Chris Guillebeau", company: "Side Hustle School" },
    { name: "Donald Miller", company: "StoryBrand" },
    { name: "Michael Hyatt", company: "Full Focus" },
    { name: "Robin Sharma", company: "The 5AM Club" },
    { name: "Jack Canfield", company: "Chicken Soup for the Soul" },
    { name: "Lewis Howes", company: "School of Greatness" },
    { name: "John C. Maxwell", company: "Leadership" }
  ],
  "Sports & Athletics": [
    { name: "Michael Jordan", company: "Jordan Brand, Hornets" },
    { name: "Magic Johnson", company: "Magic Johnson Ent." },
    { name: "Roger Federer", company: "On Running, Tennis" },
    { name: "Serena Williams", company: "Serena Ventures" },
    { name: "Venus Williams", company: "EleVen" },
    { name: "George Foreman", company: "Foreman Grill" },
    { name: "Tony Hawk", company: "Birdhouse" },
    { name: "LeBron James", company: "SpringHill Company" },
    { name: "David Beckham", company: "Inter Miami CF" },
    { name: "Derek Jeter", company: "The Players' Tribune" },
    { name: "Junior Bridgeman", company: "Bridgeman Foods" },
    { name: "Roger Staubach", company: "JLL" },
    { name: "Mathieu Flamini", company: "GF Biochemicals" },
    { name: "Wayne Gretzky", company: "Gretzky Estates" },
    { name: "Cal Ripken Jr.", company: "Ripken Baseball" },
    { name: "Jack Nicklaus", company: "Nicklaus Design" },
    { name: "Dale Earnhardt Jr.", company: "JR Motorsports" },
    { name: "Peyton Manning", company: "Omaha Productions" },
    { name: "Eli Manning", company: "Giants" },
    { name: "Steve Young", company: "HGGC" },
    { name: "Dwyane Wade", company: "Utah Jazz Owner" },
    { name: "Kevin Durant", company: "35V" },
    { name: "Allyson Felix", company: "Saysh" },
    { name: "Rob Dyrdek", company: "Dyrdek Machine" },
    { name: "Nico Rosberg", company: "Rosberg X Racing" }
  ],
  "Stars & Artists": [
    { name: "Ryan Reynolds", company: "Aviation Gin, Mint Mobile" },
    { name: "Reese Witherspoon", company: "Hello Sunshine" },
    { name: "Ashton Kutcher", company: "Sound Ventures" },
    { name: "Jessica Alba", company: "The Honest Company" },
    { name: "Oprah Winfrey", company: "Harpo Productions" },
    { name: "Dwayne \"The Rock\" Johnson", company: "Teremana Tequila" },
    { name: "Rihanna", company: "Fenty Beauty" },
    { name: "Taylor Swift", company: "Eras Tour" },
    { name: "George Clooney", company: "Casamigos" },
    { name: "Dolly Parton", company: "Dollywood" },
    { name: "Beyoncé", company: "Parkwood Entertainment" },
    { name: "Robert De Niro", company: "Nobu" },
    { name: "Selena Gomez", company: "Rare Beauty" },
    { name: "Pharrell Williams", company: "Louis Vuitton Men" },
    { name: "Jennifer Aniston", company: "LolaVie" },
    { name: "Bono", company: "Elevation Partners" },
    { name: "Nas (Nasir Jones)", company: "QueensBridge" },
    { name: "Kate Hudson", company: "Fabletics" },
    { name: "Drew Barrymore", company: "Flower Beauty" },
    { name: "Priyanka Chopra Jonas", company: "Anomaly Haircare" }
  ]
};